# safe-core/clippy.toml
# Nível de warnings (para CI: `cargo clippy -- -D warnings`)
# Apenas lint que são "deny" por padrão:
# -D clippy::pedantic -D clippy::cargo -D warnings

# Clippy conf
pedantic = true
# Permitir unwrap em testes
allow-unwrap-in-tests = true
# Exigir documentação
warn-on-all-doc-comments = true
# Checagem de segurança
check = ["security-fixes", "vulnerabilities"]
# Regras de dependência
deny = [
    "duplicate-crates",
    "wildcard-dependencies",
    "multiple-versions"
]
