/-
  band_iso — abstract core (Mathlib-free).

  The reusable heart of the Möbius `band_iso` bridge, with NO dependency on ℝ,
  topology, or Mathlib: the fundamental-domain argument that a "seam" quotient on
  a domain `D` is equivalent to an "orbit" quotient on the ambient space `X`,
  provided (covering) the domain meets every orbit, and (faithful) the orbit
  relation restricted to the domain is exactly the seam relation.

  Instantiate  X := strip,  D := Rect,  Sx := ℤ-orbit setoid,  Sd := mobiusSetoid.
  The two hypotheses below are then the ONLY ℝ-facts left to discharge, and they
  are exactly where `L > 0` and compactness of `[0,L]` enter.
-/
namespace Band

universe u v

/-- A bare bijection, to avoid pulling in Mathlib's `Equiv`. -/
structure Iso (A : Type u) (B : Type v) where
  toFun     : A → B
  invFun    : B → A
  left_inv  : ∀ a, invFun (toFun a) = a
  right_inv : ∀ b, toFun (invFun b) = b

variable {X : Type u} {D : Type v}
variable (Sx : Setoid X) (Sd : Setoid D) (ι : D → X)

/-- Fundamental-domain equivalence of quotients. -/
noncomputable def bandIso
    (hcov   : ∀ x : X, ∃ d : D, Sx.r (ι d) x)
    (hfaith : ∀ a b : D, Sx.r (ι a) (ι b) ↔ Sd.r a b) :
    Iso (Quotient Sd) (Quotient Sx) :=
  let s : X → D := fun x => (hcov x).choose
  have hs : ∀ x, Sx.r (ι (s x)) x := fun x => (hcov x).choose_spec
  { toFun :=
      Quotient.lift (s := Sd) (fun d => Quotient.mk Sx (ι d))
        (fun a b h => Quotient.sound ((hfaith a b).mpr h))
    invFun :=
      Quotient.lift (s := Sx) (fun x => Quotient.mk Sd (s x))
        (fun a b h => Quotient.sound
          ((hfaith (s a) (s b)).mp
            (Sx.iseqv.trans (hs a) (Sx.iseqv.trans h (Sx.iseqv.symm (hs b))))))
    left_inv := fun q =>
      Quotient.inductionOn q (fun d =>
        Quotient.sound ((hfaith (s (ι d)) d).mp (hs (ι d))))
    right_inv := fun q =>
      Quotient.inductionOn q (fun x =>
        Quotient.sound (hs x)) }

/-! ## Instantiation: the discrete Möbius strip

  `ℝ` is unavailable here (no Mathlib), so `bandIso` is instantiated at the
  integer model of the same structure, with period L = 4:

    X  := ℤ × Bool              -- strip: integer longitude, two transverse lanes
    g  := (x,y) ↦ (x+4, ¬y)     -- glide reflection; INFINITE order (g² = +8, no flip)
    Sx := orbit setoid of the ℤ-action generated by g
    D  := Rect = {p // 0 ≤ p.1 ≤ 4}   -- CLOSED fundamental domain (keeps the seam)
    Sd := seam setoid (orbit relation restricted to D)
-/
namespace Discrete

/-- Transverse reflection applied `n` times: flip iff `n` is odd. -/
def flip (n : Int) (y : Bool) : Bool := if n % 2 = 0 then y else !y

theorem flip_zero (y : Bool) : flip 0 y = y := if_pos (by decide)
theorem flip_one (y : Bool) : flip 1 y = !y := if_neg (by decide)
theorem flip_negone (y : Bool) : flip (-1) y = !y := if_neg (by decide)

theorem flip_add (m n : Int) (y : Bool) : flip m (flip n y) = flip (m + n) y := by
  unfold flip
  by_cases hn : n % 2 = 0
  · by_cases hm : m % 2 = 0
    · have h : (m + n) % 2 = 0 := by omega
      rw [if_pos hn, if_pos hm, if_pos h]
    · have h : ¬ ((m + n) % 2 = 0) := by omega
      rw [if_pos hn, if_neg hm, if_neg h]
  · by_cases hm : m % 2 = 0
    · have h : ¬ ((m + n) % 2 = 0) := by omega
      rw [if_neg hn, if_pos hm, if_neg h]
    · have h : (m + n) % 2 = 0 := by omega
      rw [if_neg hn, if_neg hm, if_pos h, Bool.not_not]

/-- The ℤ-action: `gⁿ (x,y) = (x + 4n, ρⁿ y)`. -/
def act (n : Int) (p : Int × Bool) : Int × Bool := (p.1 + n * 4, flip n p.2)

theorem act_zero (p : Int × Bool) : act 0 p = p := by
  obtain ⟨x, y⟩ := p
  simp only [act, flip_zero]
  have : x + 0 * 4 = x := by omega
  rw [this]

theorem act_add (m n : Int) (p : Int × Bool) : act m (act n p) = act (m + n) p := by
  obtain ⟨x, y⟩ := p
  simp only [act, flip_add, Prod.mk.injEq]
  exact ⟨by omega, trivial⟩

def orbitRel (p q : Int × Bool) : Prop := ∃ n : Int, act n p = q

def orbitSetoid : Setoid (Int × Bool) where
  r := orbitRel
  iseqv := {
    refl  := fun p => ⟨0, act_zero p⟩
    symm  := fun {p q} h => by
      obtain ⟨n, hn⟩ := h
      refine ⟨-n, ?_⟩
      rw [← hn, act_add]
      have hz : -n + n = 0 := by omega
      rw [hz, act_zero]
    trans := fun {p q r} h1 h2 => by
      obtain ⟨m, hm⟩ := h1
      obtain ⟨n, hn⟩ := h2
      exact ⟨n + m, by rw [← act_add, hm, hn]⟩
  }

/-- The CLOSED rectangle `[0,4] × Bool`. -/
def Rect : Type := { p : Int × Bool // 0 ≤ p.1 ∧ p.1 ≤ 4 }

def iota (d : Rect) : Int × Bool := d.val

/-- Seam relation: the orbit relation restricted to the rectangle. -/
def seamSetoid : Setoid Rect where
  r a b := orbitRel (iota a) (iota b)
  iseqv := {
    refl  := fun a => orbitSetoid.iseqv.refl (iota a)
    symm  := fun h => orbitSetoid.iseqv.symm h
    trans := fun h1 h2 => orbitSetoid.iseqv.trans h1 h2
  }

/-- COVERING: every strip point lies in the orbit of a rectangle point.
    This is where positivity of the period enters, via the division algorithm. -/
theorem hcov (x : Int × Bool) :
    orbitSetoid.r (iota ⟨(x.1 % 4, flip (x.1 / 4) x.2), by constructor <;> omega⟩) x := by
  obtain ⟨u, v⟩ := x
  refine ⟨u / 4, ?_⟩
  simp only [act, iota, Prod.mk.injEq, flip_add]
  refine ⟨by omega, ?_⟩
  have h : (u / 4 + u / 4) % 2 = 0 := by omega
  unfold flip
  rw [if_pos h]

/-- FAITHFULNESS is definitional here: `Sd` IS the restricted orbit relation. -/
theorem hfaith : ∀ a b : Rect, orbitSetoid.r (iota a) (iota b) ↔ seamSetoid.r a b :=
  fun _ _ => Iff.rfl

/-- `band_iso` for the discrete Möbius strip: rectangle-with-seam ≃ strip/ℤ. -/
noncomputable def mobiusIso : Iso (Quotient seamSetoid) (Quotient orbitSetoid) :=
  bandIso orbitSetoid seamSetoid iota (fun x => ⟨_, hcov x⟩) hfaith

/-- The seam is EXACTLY the Möbius edge gluing `(0,y) ~ (4,¬y)`. -/
theorem seam_is_mobius (a b : Rect) :
    seamSetoid.r a b ↔
      (a.val = b.val
        ∨ (a.val.1 = 0 ∧ b.val.1 = 4 ∧ b.val.2 = !a.val.2)
        ∨ (a.val.1 = 4 ∧ b.val.1 = 0 ∧ b.val.2 = !a.val.2)) := by
  obtain ⟨⟨ax, ay⟩, ha0, haL⟩ := a
  obtain ⟨⟨bx, by'⟩, hb0, hbL⟩ := b
  unfold seamSetoid orbitRel act iota at *
  constructor
  · rintro ⟨n, hn⟩
    have hx : ax + n * 4 = bx := congrArg Prod.fst hn
    have hy : flip n ay = by' := congrArg Prod.snd hn
    have hn3 : n = 0 ∨ n = 1 ∨ n = -1 := by omega
    rcases hn3 with rfl | rfl | rfl
    · left
      rw [flip_zero] at hy
      simp only [Prod.mk.injEq]
      exact hy
    · right; left
      rw [flip_one] at hy
      exact ⟨by omega, by omega, hy.symm⟩
    · right; right
      rw [flip_negone] at hy
      exact ⟨by omega, by omega, hy.symm⟩
  · rintro (h | ⟨h1, h2, h3⟩ | ⟨h1, h2, h3⟩)
    · refine ⟨0, ?_⟩
      rw [flip_zero] at *
      exact ⟨by omega, h.right⟩
    · refine ⟨1, ?_⟩
      rw [flip_one] at *
      exact h3.symm
    · refine ⟨-1, ?_⟩
      rw [flip_negone] at *
      exact h3.symm

/-! ### Chirality reading of the Bool fiber (proposed extension) -/

abbrev Chi := Bool
def invert (c : Chi) : Chi := !c

theorem flip_two (y : Bool) : flip 2 y = y := if_pos (by decide)

/-- One traversal of the fundamental domain flips the Bool fiber. -/
theorem traversal_inverts (p : Int × Chi) : (act 1 p).2 = invert p.2 := by
  simp only [act, flip_one, invert]

/-- Two traversals restore it. -/
theorem double_traversal_restores (p : Int × Chi) : (act 2 p).2 = p.2 := by
  simp only [act, flip_two]

/-- At the seam, the fiber is necessarily inverted. -/
theorem seam_inverts_fiber (a b : Rect)
    (ha : a.val.1 = 0) (hb : b.val.1 = 4)
    (h : seamSetoid.r a b) :
    b.val.2 = invert a.val.2 := by
  rcases (seam_is_mobius a b).mp h with h1 | h2 | h3
  · exfalso
    have : a.val.1 = b.val.1 := congrArg Prod.fst h1
    omega
  · exact h2.2.2
  · exfalso; omega


/-! ## Shader sobre a faixa: correção = descer ao quociente

  Um shader é uma função cor `ℤ × Bool → Color`. Para renderizar a BANDA
  (e não a faixa), ele precisa ser constante nas órbitas — senão os dois
  lados da costura recebem cores diferentes e a emenda fica visível.

  `Quotient.lift` só aceita a função se essa condição for provada. O
  compilador recusa um shader com costura visível.
-/
namespace Shader

abbrev Color := Int

/-- Coordenada invariante: `(x + 4·[y]) mod 8`. Absorve a meia-torção. -/
def seamCoord (p : Int × Bool) : Int :=
  (p.1 + (if p.2 then 4 else 0)) % 8

/-- INVARIÂNCIA: `seamCoord` é constante em cada órbita da ação de ℤ. -/
theorem seamCoord_invariant (n : Int) (p : Int × Bool) :
    seamCoord (act n p) = seamCoord p := by
  obtain ⟨x, y⟩ := p
  simp only [seamCoord, act, flip]
  by_cases hn : n % 2 = 0
  · rw [if_pos hn]
    cases y <;> simp <;> omega
  · rw [if_neg hn]
    cases y <;> simp <;> omega

/-- Um shader bem-definido na banda: qualquer função de `seamCoord`. -/
def stripeShader (p : Int × Bool) : Color := seamCoord p

theorem stripeShader_respects_seam (a b : Int × Bool)
    (h : orbitSetoid.r a b) : stripeShader a = stripeShader b := by
  obtain ⟨n, hn⟩ := h
  rw [← hn]
  exact (seamCoord_invariant n a).symm

/-- O shader DESCE à banda. Se a prova acima falhasse, isto não tiparia. -/
def bandShader : Quotient orbitSetoid → Color :=
  Quotient.lift stripeShader stripeShader_respects_seam

theorem bandShader_mk (p : Int × Bool) :
    bandShader (Quotient.mk orbitSetoid p) = seamCoord p := rfl

/-! ### Contraexemplo: o shader ingênuo tem costura visível -/

/-- Colorir só pela faixa transversal. Parece razoável e está errado. -/
def laneShader (p : Int × Bool) : Color := if p.2 then 255 else 0

/-- Os dois lados da costura são o MESMO ponto da banda... -/
theorem seam_points_are_identified :
    orbitSetoid.r ((0 : Int), true) ((4 : Int), false) :=
  ⟨1, by simp only [act, flip]; norm_cast⟩

/-- ...mas o shader ingênuo lhes dá cores diferentes: EMENDA VISÍVEL. -/
theorem laneShader_has_visible_seam :
    laneShader ((0 : Int), true) ≠ laneShader ((4 : Int), false) := by
  simp [laneShader]

/-- Logo `laneShader` não pode descer ao quociente. -/
theorem laneShader_does_not_descend :
    ¬ (∀ a b : Int × Bool, orbitSetoid.r a b → laneShader a = laneShader b) := by
  intro h
  exact laneShader_has_visible_seam (h _ _ seam_points_are_identified)

end Shader

end Discrete
end Band
